-- AlterEnum
-- 添加新的 TransactionType 枚举值
ALTER TYPE "TransactionType" ADD VALUE IF NOT EXISTS 'LIQUIDITY_INJECTION';
ALTER TYPE "TransactionType" ADD VALUE IF NOT EXISTS 'LIQUIDITY_RECOVERY';
ALTER TYPE "TransactionType" ADD VALUE IF NOT EXISTS 'MARKET_PROFIT_LOSS';

